### ISSUE TITLE
Please open source the cardboard code

### ISSUE THREAD

**Issue by timsuchanek** [googlesamples/cardboard-java#11] opened 2014-09-21 17:31 UTC
Hi,
this is really a great project. But please open source the code, that's in the cardboard sdk jar.
You can decompile the Java Byte Code easily anyway, so why not open source it?

We're currently trying to rebuild the lens distortion shader with ThreeJS.
Therefore the real source code would really help.

Thanks!

**Comment by westonized** [comment] 2015-01-12 16:23
+5

**Comment by zfarm** [comment] 2015-01-12 16:46
We are trying to expand the available screen space. We are useing the latest XX high def resolution phone LG G3 2560 x 1440 and the sdk locks us off at a "cropped" size. Any ideas on how to expand that to full screen

**Comment by rsanchezsaez** [comment] 2015-01-12 17:58
As a stop-gag until Google releases the original source, I decompiled the bytecode using Luyten. [This form](https://github.com/rsanchezsaez/cardboard-java) compiles and runs purely from source (tested on Android Studio 1.0.2).

A sucky problem is that all the `GL_CONSTANTS` are (expectedly) decompiled to their integer values instead of to their `#define` names. This is specially evident on `DistortionRenderer.java`.

If anybody feels like replacing those back and submitting a pull request, that'd be great.

**Comment by dcerisano** [comment] 2015-01-12 21:53
Looks like buddy over here has decomplied the vrtoolkit as well.
Thanks buddy!
https://github.com/Zomega/Cardboard/tree/master/src/com/google/vrtoolkit/cardboard

**Comment by westonized** [comment] 2015-01-13 09:11
Well done @rsanchezsaez Thanks!

**Comment by rsanchezsaez** [comment] 2015-01-13 10:19
I think @Zomega's decompilation is from an older CardboardSDK version (it's 7 month's old). Mine's from the latest one. :-)

**Comment by dcerisano** [comment] 2015-01-13 22:13
A good point. Google may be preparing a major version upgrade to vrtoolkit, so using any previous version is risky. That may be why they have not released the source yet.

I noticed the design of the interfaces need improvement to make them workable.

**Comment by dcerisano** [comment] 2015-01-13 22:30
A good point. Google may be preparing a major version upgrade to vrtoolkit, so using any decompiled previous version is risky. That may be why they have not released the source yet.

Noticed the design of the some of the interfaces needs improvement to make them workable. 

For eg.  lack of a fast manual drift reset method is a major issue.  
Also the jitter caused by the head tracker sensor sampling algo is unnerving. 
Had to integrate with Rajawali for an OpenGL scenegraph framework which vrtoolkit desperately needs. The quaternion maths functions helped in overcoming the drift and jitter.

Hope they include solutions for these in any upcoming upgrades.

**Comment by rsanchezsaez** [comment] 2015-01-14 19:13
Hey,

I just got a [CardboardSDK iOS port](https://github.com/rsanchezsaez/CardboardVR-iOS) (I completed the work started by @2equinox2k) up and running with the Treasure example. Some small features are missing, but it works quite alright. I'll be working more on it later.

Cheers!

**Comment by rahul27** [comment] 2015-02-07 00:51
+1

**Comment by D3m0n92** [comment] 2015-02-27 07:58
+1

**Comment by mjsibbald** [comment] 2015-04-15 00:13
Is there anybody that has done it wiith the latest version? I would be for ever grateful.

**Comment by dcerisano** [comment] 2015-04-15 00:46
I have heard that the latest version has been open-sourced by Google.

**Comment by mjsibbald** [comment] 2015-04-15 00:49
That would be nice.... were can we find it?

**Comment by dcerisano** [comment] 2015-04-15 01:53
It is a rumor. Perhaps you could confirm or disprove it.

**Comment by lrq3000** [comment] 2015-09-17 12:29
+1, please open source.

**Comment by D3m0n92** [comment] 2015-09-17 12:30
Open source! +1

**Comment by udev** [comment] 2015-09-17 15:28
+1

**Comment by dcerisano** [comment] 2015-09-17 17:54
I noticed that the latest cardboard.jar just went from 200K to 600K due to a new binary:
vrtoolkit.so

I write my own renderers in openGLES and was able to remove the binary, and everything still worked (head tracking, etc).

I suspect that they have ported their renderer to C++ and NDK. This seems to be a proprietary move and does not bode well for opensourcing the codebase.

**Comment by Zomega** [comment] 2015-09-17 20:51
@rsanchezsaez

That's correct: My decompilation was made a day or two after the Cardboard launched and was never built successfully, so it's probably not the best place to start.

I work at Google now, so I can't keep working on this sort of thing. Glad to see people excited about VR though!

**Comment by serghov** [comment] 2015-10-18 09:05
+1

**Comment by njam** [comment] 2015-10-18 12:05
+1

**Comment by luav** [comment] 2015-10-19 14:24
+1

**Comment by fcoulombe** [comment] 2015-10-20 23:28
+1

**Comment by boyce-ywr** [comment] 2015-10-21 16:53
+

**Comment by dcerisano** [comment] 2015-10-23 17:06
https://github.com/googlesamples/cardboard-java/issues/17

**Comment by jiangzhouq** [comment] 2015-11-11 09:53
Come on

**Comment by dcerisano** [comment] 2015-11-11 15:45
Considering how big VR is going to be, google is not likely to opensource all of the sdk.
Don't forget that ads have not yet been integrated, and that requires closed source solutions.
You can always build your own sdk, but it won't be 'inside' googles' VR 'metaverse'.

**Comment by nathanmartz** [comment] 2016-01-22 04:14
We appreciate the feedback, but closing this as it's not really an "issue" with the Cardboard SDK.

**Closed by nathanmartz** 2016-01-22 04:14 UTC

**Comment by gwald** [comment] 2016-04-08 01:43
+1

**Comment by babysource** [comment] 2016-04-08 03:51
+1

**Comment by jacksonkr** [comment] 2016-06-22 22:20
+1

**Comment by zhxj22** [comment] 2016-07-07 13:07
+1, really.

**Comment by sp-wisebits** [comment] 2016-08-11 07:21
> We appreciate the feedback, but closing this as it's not really an "issue" with the Cardboard SDK.

What is it then?

**Comment by jisuz** [comment] 2016-08-18 02:55
+1

**Comment by Lingyuezhixing** [comment] 2016-08-28 04:47
+1

**Comment by NanLen** [comment] 2016-09-09 07:05
+1

**Comment by jzhu1224** [comment] 2016-09-12 09:19
+1

**Comment by tiantian20007** [comment] 2016-09-16 06:34
+1

**Comment by ejoebstl** [comment] 2016-11-22 11:00
+1

**Comment by CarlLee** [comment] 2016-12-11 13:27
+1

**Comment by bluefish625** [comment] 2017-05-11 07:38
+1

**Comment by dcerisano** [comment] 2017-05-13 19:44
Gee, wouldn't it be great if there was an opensource mobile VR library that did not use Cardboard, Daydream, Gear libraries at all, but ran on all of these devices?
