### ISSUE TITLE
Disabling DistortionCorrection causes errors in 0.5.2

### ISSUE THREAD

**Issue by zbendefy** [googlesamples/cardboard-java#21] opened 2015-02-28 19:43 UTC
Hello!

There seems to be an issue introduced in api version 0.5.2 (it did not occur in 0.5.1)

TreasureHunt runs all fine, however when i add this line: `cardboardView.setDistortionCorrectionEnabled(false);` into the Activity's onCreate() method, the screen becomes messed up. 

I noticed this first in my app which offers an option to disable distortion correction (to improve performance). Can someone confirm this error? My phone is a galaxy note 3 (adreno330)

edit: i tried on a note2 (mali400mp4) and the same error occurs there as well.
edit2: i tried on a zte blade 3 (adreno200+) and the same error occurs there as well.

**Comment by veonua** [comment] 2015-03-02 23:40
mess confirmed for Nexus5

**Comment by svenhenrik** [comment] 2015-04-01 05:15
Confirmed on LG G2. If I get the view and turn off distortion in onSurfaceCreated I get an undistorted display, but it is still not correctly rendered. The left view takes up ~60% of the screen instead of 50%, but the divider and gear icon are still centered.

**Comment by keaukraine** [comment] 2015-04-04 10:28
I confirm both garbled rendering and incorrect proportion for left/right views.
Devices - Google Nexus 4 and LG G3.

**Comment by mjsibbald** [comment] 2015-04-15 00:09
Same here. Tested on Note 4

**Comment by mjsibbald** [comment] 2015-04-15 00:21
Just tested the previous version. That one is working. Please fix this. in the latest version

**Comment by dav-cz** [comment] 2015-04-16 17:37
Thanks for the reports!
This should be now fixed in v0.5.3.

**Comment by mjsibbald** [comment] 2015-04-16 17:52
Hi David,

Yes it does not give me the distorted image anymore. But the effect is very different from 0.5.2. There is a big bar in the middle now and on bigger resolution it's showing even more space on top and the sides. 

In 0.5.2. it gave me fullscreen split. If you know what I mean. I probably know why this is happening, besides the big bar in the middle. I really needed the the splitscreen to fill the entire screen. 

Not sure if this helps in anyway, because I appreciate the fix very much. I would prefer it to be some kind of option. like fit cardbaord true, or fullscreenVR = true.

Thank you!

**Comment by smdol** [comment] 2015-04-16 17:57
The black area around the edges is an artifact of the Cardboard viewer device that your phone is paired with.  It is based on the actual area of the screen you can see through the lenses.  You control this by scanning a QR code in the Cardboard app.  Some viewers like the Go4d can see the whole screen.

**Comment by mjsibbald** [comment] 2015-04-16 17:58
Is there a way I can set this programmatically?

**Comment by dav-cz** [comment] 2015-04-16 21:02
Hi mjsibbald, 
Glad to hear it works better for you now :)
As smold explained, we try to only render the parts of the screen that are visible through the lenses, which saves rendering power.  And no, this can't be disabled programmatically.

If you have a headset that actually lets you see more than what the SDK displays, and if your headset doesn't have a parameter QR code, you can try to create your own one by visiting this calibration tool page we just launched.
https://www.google.com/get/cardboard/viewerprofilegenerator.html

Hope that helps!

**Closed** 2015-04-19 11:50 UTC
