### ISSUE TITLE
v0.5.6 SDK memory leak

### ISSUE THREAD

**Issue by esminis** [googlesamples/cardboard-java#29] opened 2015-09-17 15:07 UTC
MainActivity is leaked, even in sample app same happens. From memory dump I see that leak GC root is Native Stack.

**Comment by R1ck77** [comment] 2015-11-23 15:39
Confirmed in v0.5.8 too: I didn't a thorough check of the source of the problem as you did, but I can confirm that the activity is leaking (as it also happened with the previous java-based implementations)...

Btw, are we actually *writing to anyone* at all? Is anyone in the developer's group **reading this** or are we wasting our time?

Because there are like 26 bugs, not 2600, which means 5 for each contributor, and after a cursory search, not a single one I have browsed had a developer assigned to it, or received any kind of feedback (even just a "Thank you, we are working on that!"). 

It' very sad to say, but for being a technology Google is investing so much on, until now the developers support quite sucks. :(

**Comment by dav-cz** [comment] 2015-11-23 16:59
Hi, very sorry for the lack of response. Our team is better staffed now so we'll have better dev support. Thanks esminis for the original report, and thanks R1ck77 from bringing this issue to our attention. We will definitely look into it.

**Comment by R1ck77** [comment] 2015-11-23 17:31
Hi David, 

thanks for the ACK: I'm very glad to hear that the support for the SDK is growing, and I look forward for the issue to be resolved (or for any details on the matter that could help us work around the issue with reflection, as we did with this one: https://github.com/googlesamples/cardboard-java/issues/19). 

Have a nice day! 
Riccardo

**Comment by dav-cz** [comment] 2015-12-02 22:48
Thanks for tips Riccardo, that was helpful! This issue should be fixed in the next version.

**Comment by R1ck77** [comment] 2015-12-02 23:49
You're welcome: I'm looking forward for the next version  :)

Cheers

**Comment by R1ck77** [comment] 2015-12-22 19:46
Sorry to bother you (and glad to see a fair amount of activity on the tracker), I know you are busy, but is there any heads up on this issue?

I'm asking because I was wondering if there is something we can do via reflection to work around the problem, even though it seems located in the native layer...

**Comment by dav-cz** [comment] 2015-12-23 17:24
The issue is fixed in our internal repo, the fix will be pushed on github for our next public release, which should happen some time after the holiday break.
You're correct, one of the sources for the leak was in our native code at the jni level, which you won't be able to fix via reflection.

**Comment by R1ck77** [comment] 2015-12-23 19:04
Thank you very much for the prompt and kind answer and keep up the good work (and have some great holidays)! 

I'll stop pestering you now, and wait *patiently* for the next release :)

**Comment by R1ck77** [comment] 2016-01-14 10:23
Checked the new release and works like a charm (for saying nothing of all other goodies, like the sound support)! Thank you!

**Comment by dav-cz** [comment] 2016-01-21 23:36
Thanks for the help and nice words, @R1ck77! Closing this bug now.

**Closed by dav-cz** 2016-01-21 23:36 UTC
